name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'liquidgen-server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'liquidgen-server/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Format
      run: |
        cd liquidgen-server
        cargo fmt -- --check

    - name: Clippy
      run: |
        cd liquidgen-server
        cargo clippy -- -D warnings

    - name: Run Tests
      run: |
        cd liquidgen-server
        cargo test

    - name: Build
      run: |
        cd liquidgen-server
        cargo build --release

  security:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run Security Audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}